### PR TITLE
Trash collect bug fix

### LINKED ISSUE #8: trash-bags should disappear after collecting it
Right now, the cans after collecting are not getting destroyed, even after calling the destroy function.
It's some logic error in the code may be.

### PR DESCRIPTION
**Pull request by DebugAgrawal**
> ### After the diver collects the trash, trash gets destroyed/collected 🚩 Resolves #8 

---
Olaf-Swim-Fix
---

### CODE REVIEW

**Review by anjalisoni3655 — APPROVED** [review]
Just one line change? Can you explain in brief what exactly did you do?

**Comment by DebugAgrawal** [comment]
> Just one line change? Can you explain in brief what exactly did you do?

`collider.gameObject.transform.position = new Vector3(50f,502f,-50f);`

#### Using the `transform.position` we are changing the position of each trash-bag to a new value, instead, if we go with `Destroy(gameObject)` the trash-bag (object) is destroyed due to which the next scene doesn't load as we are invoking the single trash-bag (object) multiple times

**Comment by anjalisoni3655** [comment]
> > Just one line change? Can you explain in brief what exactly did you do?
> 
> `collider.gameObject.transform.position = new Vector3(50f,502f,-50f);`
> 
> #### Using the `transform.position` we are changing the position of each trash-bag to a new value, instead, if we go with `Destroy(gameObject)` the trash-bag (object) is destroyed due to which the next scene doesn't load as we are invoking the single trash-bag (object) multiple times
> 

Oh I got it.

**Review by anjalisoni3655 — APPROVED** [review]
Ready to be merged and also can you update the deployed game url in the readme with the new one.

**Pull request merged**
